### ISSUE TITLE
bump up Jquery version

### ISSUE THREAD

**Issue by harshvkarn** [openebs/ci-e2e-dashboard#11]
- Currently, jquery version is v1.11.1
- Bump up jquery to 3.x

**Comment by Rupeshiya** [comment]
should I change https://github.com/openebs/ci-e2e-dashboard/blob/master/src/assets/js/jquery-1.11.1.min.js  to https://code.jquery.com/jquery-migrate-3.0.1.min.js  or any other changes required ?

**Comment by Rupeshiya** [comment]
I would like to fix this. Should I ?

**Comment by harshvkarn** [comment]
@Rupeshiya please go ahead, and do the required changes! But after bumping up the version do make sure that everything is working fine.

**Comment by MaskyS** [comment]
@harshvkarn, should this issue be closed, since this project already seems to be using jquery 3.x ? https://github.com/openebs/ci-e2e-dashboard/blob/c3cd881e30628b01ef44699d207ff3001bafa45c/package.json#L29

**Comment by harshvkarn** [comment]
@MaskyS Yes!
