### ISSUE TITLE
Highlight the selected button in E2E Pipelines

### ISSUE THREAD

**Issue by chandankumar4** [openebs/ci-e2e-dashboard#63]
Highlight the buttons when it is in active state for E2E pipelines inside CI/E2E Dashboard tab

![image](https://user-images.githubusercontent.com/28861964/47252747-0c6d2680-d467-11e8-8bd6-6a1b69c8f956.png)

Like in upper image GKE is selected pipelines so it should be highlighted like underline or change the background color.

Reference for that code available - https://github.com/openebs/ci-e2e-dashboard/tree/staging/src/app/table

**Comment by theragnarpatel** [comment]
-- working on user clicked any E2E Pipeline. problem: need to highlight clicked particular E2E  pipeline.

**Comment by chandankumar4** [comment]
Great! Thanks @theragnarpatel

**Comment by mr-yamraj** [comment]
I would like to work on this.
Can you please specify exactly what needs to be done.
In my view, I need to change the Background color of the text "GKE" on the right side column below the logo. Is that correct?

**Comment by theragnarpatel** [comment]
> I would like to work on this.
> Can you please specify exactly what needs to be done.
> In my view, I need to change the Background color of the text "GKE" on the right side column below the logo. Is that correct?

No, you need to btn highlight when user click that particular btn at time. so user can see which one clicked by them.

**Comment by chandankumar4** [comment]
This issue is already fixed! I'm closing this issue
