### ISSUE TITLE
Set default selected E2E pipeline for GKE when webiste load

### ISSUE THREAD

**Issue by chandankumar4** [openebs/ci-e2e-dashboard#96]
## what needs to be done

- Set the GKE pipeline selected as default when the website load

![image](https://user-images.githubusercontent.com/28861964/47520061-c53ec580-d8ac-11e8-8c33-2748470dead6.png)

**Comment by subeshf** [comment]
please go to the following link you can find solution 


https://cloud.google.com/solutions/continuous-delivery-jenkins-kubernetes-engine

**Comment by aashish-ak** [comment]
![openebs](https://user-images.githubusercontent.com/21988675/47600168-86a72900-d9da-11e8-9400-30b670b772c9.png)
@chandankumar4  The GKE pipeline is already default in mine.

**Comment by chandankumar4** [comment]
Right! @aashish-ak GKE deatil is showing in right side but it is not selected like upper image, underline with selected row

**Comment by aashish-ak** [comment]
@chandankumar4 Fixed the issue, please merge as soon as you can :smile:

**Comment by aashish-ak** [comment]
Fixed the row bar too @chandankumar4 , please review the PR now :smiley:
